# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    identifier: 4c34839e
    url: /
    weight: 10
  - name: Research
    identifier: 7d948abc
    url: /#research
    weight: 20
  - name: Events
    identifier: 884b15b3
    url: /#events
    weight: 30
  - name: Experience
    identifier: a6096238
    url: experience/
    weight: 40
  - name: Papers
    identifier: papers
    url: /papers/
    weight: 50
  - name: Presentations
    identifier: presentations
    url: /presentations/
    weight: 60
  - name: Projects
    identifier: 9c148d17
    url: projects/
    weight: 70
  - name: Learning
    identifier: 66a3ba8b
    url: /learning/
    weight: 80
